"""
Constructs scikit-learn Pipeline objects from discrete genome arrays and continuous hyperparameters.
"""

from typing import Any, Dict, Optional

import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MaxAbsScaler, RobustScaler, StandardScaler
from sklearn.svm import LinearSVC


def build_pipeline(
    scaler_type: Optional[str],
    dim_reduction_type: Optional[str],
    vectorizer_type: str,
    model_type: str,
    ngram_range: str,
    max_features: Any,
    params: Dict[str, Any],
    random_state: int = 42,
) -> Pipeline:
    """Constructs a sequential sklearn Pipeline based on architectural genes and tuned hyperparameters."""
    steps = []

    # Text Vectorization
    # Handle numpy string types generated by np.random.choice during mutation
    if isinstance(ngram_range, (str, np.str_)):
        min_n, max_n = map(int, str(ngram_range).split("-"))
    else:
        min_n, max_n = map(int, ngram_range)

    # Cast literal "None" strings back to Python NoneType
    if str(max_features) == "None":
        max_feat = None
    else:
        max_feat = int(max_features)

    if vectorizer_type == "tfidf":
        vectorizer = TfidfVectorizer(
            ngram_range=(min_n, max_n),
            min_df=params.get("min_df", 1),
            max_df=params.get("max_df", 1.0),
            max_features=max_feat,
        )
    elif vectorizer_type == "count":
        vectorizer = CountVectorizer(
            ngram_range=(min_n, max_n),
            min_df=params.get("min_df", 1),
            max_df=params.get("max_df", 1.0),
            max_features=max_feat,
        )
    else:
        raise ValueError(f"Unknown vectorizer type: {vectorizer_type}")
    steps.append(("vectorizer", vectorizer))

    # Feature Scaling
    # with_mean=False and MaxAbsScaler are utilized to preserve sparse matrix structures and prevent memory exhaustion
    if scaler_type == "standard":
        steps.append(("scaler", StandardScaler(with_mean=False)))
    elif scaler_type == "maxabs":
        steps.append(("scaler", MaxAbsScaler()))
    elif scaler_type == "robust":
        steps.append(("scaler", RobustScaler(with_centering=False)))

    # Dimensionality Reduction
    # TruncatedSVD is leveraged for sparse matrices
    # SelectKBest acts as an interpretable feature filter
    if dim_reduction_type == "pca":
        n_components = params.get("pca_n_components", 50)
        steps.append(("dim_reduction", TruncatedSVD(n_components=n_components)))
    elif dim_reduction_type == "select_k_best":
        k = int(params.get("k_best_k", 100))
        steps.append(("dim_reduction", SelectKBest(f_classif, k=k)))

    # Classification
    if model_type == "logistic":
        model = LogisticRegression(
            C=params.get("C", 1.0),
            solver="saga",
            penalty="l2",
            max_iter=params.get("max_iter", 1000),
            n_jobs=1,
            random_state=random_state,
        )
    elif model_type == "naive_bayes":
        model = MultinomialNB(alpha=params.get("alpha", 1.0))
    elif model_type == "svm":
        penalty = params.get("penalty", "l2")
        # L1 penalty requires primal formulation
        # L2 uses dual=True for sparse text unless scaled to dense
        dual = (
            False
            if penalty == "l1"
            else ("auto" if scaler_type == "standard" else True)
        )
        model = LinearSVC(
            C=params.get("C", 1.0),
            penalty=penalty,
            dual=dual,
            max_iter=params.get("max_iter", 1500),
            random_state=random_state,
        )
    else:
        raise ValueError(f"Unknown model type: {model_type}")

    steps.append(("classifier", model))
    return Pipeline(steps)
